### PR TITLE
Added iOS 16.6

### PR DESCRIPTION
**Pull request by yangKJ**

### CODE REVIEW

**Review by nirav-resideo — APPROVED** [review]

**Comment by abdoerrahiem** [comment]
Do you have IOS 15.8?

**Comment by Parthkanpara** [comment]
can you please give us iOS 15.8 device support file.

**Comment by aikins01** [comment]
Can this be merged in to encourage adding future ones

**Review by yangKJ — COMMENTED** [review]
Add iOS 16.6

**Comment by filsv** [comment]
@yangKJ Thanks, added.

**Pull request merged**
